### ISSUE TITLE
Specify a MSRV

### ISSUE THREAD

**Issue by auronandace** [nwrenger/omega#1]
Adding a field for your Minimum Supported Rust Version can be handy for people who wish to package your application for a linux distribution.

The field name in your `Cargo.toml` file under the `[package]` section is `rust-version`.

**Comment by nwrenger** [comment]
Added in [this commit](https://github.com/nwrenger/omega/commit/f941627fb961617cd987ac2f00dd0162ebfafcda) using the `cargo-msrv` tool
