### ISSUE TITLE
Attempted compile on Void Linux

### ISSUE THREAD

**Issue by auronandace** [nwrenger/omega#2]
After trying to compile on void I get this error about the clippers dependency:

```
error: could not find native static library `z`, perhaps an -L flag is missing?

error: could not compile `clippers` (lib) due to 1 previous error
```

I have `zlib-devel` and `libX11-devel` installed so I'm not sure what else I need.

**Comment by nwrenger** [comment]
Yeah, had the same issues with clippers on void Linux. The clippers crate itself is a binding layer for the C++ library [clip](https://github.com/dacap/clip). But the requirements are met for the clip library by installing libX11-devel. So currently, I can’t help you there any further, I have to look more deep into that when I have more time.

**Comment by nwrenger** [comment]
Fixed in [this commit](https://github.com/nwrenger/omega/commit/6edf4cc6972e31547283bded2d8553d1f54cdcd4). I am using now a different crate for the clipboard, called `arboard`.
